### PR TITLE
update to v1.1.1

### PR DESCRIPTION
**Pull request by patrick-ogrady**

### CODE REVIEW

**Review by rovechkin1 — COMMENTED** [review]
lgtm

**Comment by patrick-ogrady** [comment]
Sorry, @rovechkin1! Was just playing around on a fork and accidentally created a PR upstream. You can disregard. Nice work on this project btw!

**Comment by rovechkin1** [comment]
np probably a good change to make anyway, as long as it was tested

**Comment by patrick-ogrady** [comment]
I deployed on gcloud with that version-based tag but think using a digest is a safer strategy for production.

**Pull request closed without merging**
